### ISSUE TITLE
㑠 is not simplified form of 㒘.

### ISSUE THREAD

**Issue by kunki** [cjkvi/cjkvi-variants#1]
In the file `cjkvi-simplified.txt`, [Line 47](https://github.com/cjkvi/cjkvi-variants/blob/master/cjkvi-simplified.txt#L47) and [Line 8629](https://github.com/cjkvi/cjkvi-variants/blob/master/cjkvi-simplified.txt#L8629) should be removed, since 㒘's simplified form is not 㑠 but ⿰亻竖.

**Comment by kunki** [comment]
[Line 210](https://github.com/cjkvi/cjkvi-variants/blob/master/cjkvi-simplified.txt#L210) has the same problem.

**Comment by kawabata** [comment]
Thank you for your report.  For Line 210 problem, I've found that this comes from GB 7589
simplified form vs. traditional form inconsistency.  Probably GB 7589 original version had a mistake,
as shown in the figure.
![tmp](https://cloud.githubusercontent.com/assets/217020/8459591/5b476538-2059-11e5-8886-90579f27279e.png)

**Comment by kunki** [comment]
Thanks for your timely reply, I'll check it later if there is other problem similar to this one in the file.
